title: Holistic Bodywork - Marcel Hösl
email: "info@bodyworkmarcel.com"
tagline: "Thai Yoga Massage | Chi Nei Tsang | Fußreflexzonen Massage | Funktionelle Massage | Liquid Flow (Wassermassage) | Aromaöl Massage | Mentale Entspannung"
baseurl: ""
url: "http://bodyworkmarcel.github.io"
paginate: 1
github_username: bodyworkmarcel

gems:
  - jekyll-paginate

markdown: kramdown
permalink: pretty
